### PR TITLE
Update requirements for docs

### PR DESCRIPTION
**Pull request by vlipovac**
## Proposed changes

Include relevant packages for documentation building in `requirements-dev.txt`, see #774 .

## Types of changes

- [X] Minor change (e.g., dependency bumps, broken links, etc).
- [ ] Bugfix (non-breaking change which fixes an issue).
- [ ] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).
- [ ] Testing (contribution related to testing of existing or new functionality).
- [ ] Documentation (contribution related to adding, improving, or fixing documentation).
- [ ] Maintenance (e.g., improve logic and performance, remove obsolete code, etc).
- [ ] Other: 

## Checklist

- [ ] The documentation is up-to-date.	
- [ ] Static typing is included in the update.
- [X] This PR does not duplicated existing functionality.
- [ ] The update is covered by the test suite (including tests added in the PR).

### CODE REVIEW

**Review by OmarDuran — COMMENTED** [review]
Thank your contribution. I think we should include those dependencies only if they are strictly required on automated builds of the documentation. Otherwise, we can relax on required those dependencies.

**Comment by IvarStefansson** [comment]
> > Thank your contribution. I think we should include those dependencies only if they are strictly required on automated builds of the documentation. Otherwise, we can relax on required those dependencies.
> 
> Hi,
> 
> the automatized building of documentation will certainly need these packages, but they (like any package) can be accessed separately in the .yml files. I though `requirement-dev.txt` also serves as an overview for developer, telling them which packages they need for developing activities?

I agree the -dev should contain what is needed for developing. And documentation is a mandatory part of that.

**Review by OmarDuran — APPROVED** [review]

**Comment by OmarDuran** [comment]
> > Thank your contribution. I think we should include those dependencies only if they are strictly required on automated builds of the documentation. Otherwise, we can relax on required those dependencies.
> 
> Hi,
> 
> the automatized building of documentation will certainly need these packages, but they (like any package) can be accessed separately in the .yml files. I though `requirement-dev.txt` also serves as an overview for developer, telling them which packages they need for developing activities?

**Comment by vlipovac** [comment]
> @vlipovac I ran the following test with the local modification on `dockerfiles/base/Dockerfile`: `RUN wget https://raw.githubusercontent.com/pmgbergen/porepy/update-issue-774/requirements.txt && \ wget https://raw.githubusercontent.com/pmgbergen/porepy/update-issue-774/requirements-dev.txt` I have found that for `sphinx-rtd-theme` the base Docker image generation fails because the package is not available from current conda channels. Perhaps we just simply remove `sphinx-rtd-theme` from requirements-dev.txt. What is your opinion on it?

Hei @OmarDuran ,
Jhabriel told me yesterday that I should try that, but I did not have the time.

I agree, even more, let me abort this PR until the automatization is implemented.

**Comment by jhabriel** [comment]
I believe the right move here is to create a `requirements_doc.txt`. Then, people who wants to generate the docs could easily pip install such requirements.

That being said, I suggest we isolate  the docker build from the docs generation, and keep it as it is, i.e., install only packages present in `requirements.txt` and `requirements_dev.txt`.

Note that this is the approach used for numpy, for example: https://github.com/numpy/numpy/blob/main/doc_requirements.txt

**Comment by jhabriel** [comment]
Also, may I suggest to add the `docs` folder to `gitignore`. In this way, we won't have to deal with the dozens of files generated after `make html`.

**Comment by OmarDuran** [comment]
Absolutely agree with all your points.

**Comment by vlipovac** [comment]
I am aborting this PR after a discussion with Jhabriel and Omar. We will implement another solution for this (see Jhabriels comments).

**Pull request closed without merging**
