### PR TITLE
STY/BLD: Comply with mypy and freeze max numba version

### PR DESCRIPTION
**Pull request by jhabriel**
## Proposed changes

Describe the big picture of your changes here to communicate to the maintainers why the pull request is necessary and why we should accept it. If it fixes a previously reported bug, be sure to link to that issue. Please also summarize the changes to the code.

## Types of changes

What types of changes does your code introduce to PorePy?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Testing (contribution related mainly to testing of existing functionality)
- [ ] Documentation update (if none of the other choices apply)
- [x] Other: non-breaking change to please mypy and freeze dependency version

## Checklist

_Enter one &check; (`&check;`) in each row. The table can be updated after creating the PR._

||Yes|No|NA|
|---|---|---|---|
|The update is covered by the test suite |_|_|x|
|The documentation is up-to-date |_|_|x|
|I have not duplicated existing functionality |_|_|x|

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered. Also add any further comments which might be of interest to the reviewer or the user community.

### CODE REVIEW

**Comment by jhabriel** [comment]
On a completely unrelated issue, the installation process of GitHub Actions is failing for Python 3.10.

The reason is that `pip` is installing (I have no idea why) the wrong version of `setuptools`. As explained in https://github.com/numba/numba/pull/8356, `numba 0.56.2` was forced to use `setuptools < 60`. However, pip (only in Python 3.10 though) is installing `setuptools 63.2.0`. The collection is correct (see line 64-66 from the logs of Installing PorePy -> https://github.com/pmgbergen/porepy/runs/8156533360?check_suite_focus=true) although the installation is incorrect (see line 99 from the logs of Installing PorePy -> https://github.com/pmgbergen/porepy/runs/8156533360?check_suite_focus=true).

What is astonishingly weird is that this is only happening for Python 3.10. Despite the restrictive requirement by Numba of enforcing `setuptools < 60`, it seems that it is `pip` the one to blame in this case.

Although not elegant, the natural fix is to freeze the Numba version to ` 0.53.0 <= numba < 0.56.2` and hope that this is solved in the near future.

**Comment by jhabriel** [comment]
I will add the changes to `requirements.txt` and `requirements-dev.txt`.

**Comment by jhabriel** [comment]
Excellent, the fix worked. @keileg, by all means, feel free to approach the fix differently if you know how.

**Review by keileg — APPROVED** [review]
What a way to spend a beautiful Sunday, @jhabriel. 

Fixating the requirements will have to do for now; please remind me to check if we can unfix it later. Thanks for the effort!

**Comment by jhabriel** [comment]
For the record, it was a Saturday evening. 

Could you merge the PR? I'll be AFK for most part of the day.

**Pull request merged**
