### PR TITLE
Benchmark-tutorial-fixes

### PR DESCRIPTION
**Pull request by IvarStefansson**
## Proposed changes

Minor bug fix and documentation improvement.

## Types of changes

What types of changes does this PR introduce to PorePy?
_Put an `x` in the boxes that apply._

- [ ] Minor change (e.g., dependency bumps, broken links).
- [x] Bugfix (non-breaking change which fixes an issue).
- [ ] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).
- [ ] Testing (contribution related to testing of existing or new functionality).
- [x] Documentation (contribution related to adding, improving, or fixing documentation).
- [ ] Maintenance (e.g., improve logic and performance, remove obsolete code).
- [ ] Other:

## Checklist

_Put an `x` in the boxes that apply or explain briefly why the box is not relevant._

- [x] The documentation is up-to-date.
- [ ] Static typing is included in the update.
- [x] This PR does not duplicate existing functionality.
- [ ] The update is covered by the test suite (including tests added in the PR). Doesn't seem like it. Otherwise, it should have failed before the fix.
- [ ] If new skipped tests have been introduced in this PR, `pytest` was run with the `--run-skipped` flag.

### CODE REVIEW

**Comment by IvarStefansson** [comment]
@IngridKJ, could you please have a look at the addition in the Readme?

**Review by keileg — APPROVED** [review]

**Comment by keileg** [comment]
Approved, assuming that @IngridKJ agrees with the change in the Readme.

**Comment by IngridKJ** [comment]
Had a look at the readme, and the only problem was a slight typo. We refer to the flux discretization tutorial by numbering when talking about the stress discretization. So I updated it from 14 (old number) to 15 (new number), but otherwise it looks fine:)

**Comment by IvarStefansson** [comment]
> Had a look at the readme, and the only problem was a tiny typo. We refer to the flux discretization tutorial by numbering when talking about the stress discretization. So I updated it from 14 (old number) to 15 (new number), but otherwise it looks fine:)

Thanks!

**Pull request merged**
