### PR TITLE
Update exporter

### PR DESCRIPTION
**Pull request by alessiofumagalli**
Please try to merge this update and use it. 
There are two example in 
- examples/example1/benchmark1/test_vem.py
- examples/papers/arXiv:1711.01818/example_5_2_1.py
The tests fail because of the new interface is not updated everywhere. Once we finalise the interface I'll fix the other files and merge.
Ciao

### CODE REVIEW

**Comment by rbe051** [comment]
I like this very much! I expect most of the tests that imports exporter and fail do in fact not need to import it at all

**Comment by alessiofumagalli** [comment]
You're right Runar, probably we simply need to remove them.

**Comment by alessiofumagalli** [comment]
I'm updating also the elliptic and parabolic and compressible. soon I'll send the new version, please try before accept the new version.

**Comment by keileg** [comment]
Makes a lot of sense to me. 

I'm working on an update to the sort_points function, but that I can do independently.

**Comment by alessiofumagalli** [comment]
the branch does not fail any more. I need another approval to merge it :)

**Pull request merged**
