### PR TITLE
Benchmark 2

### PR DESCRIPTION
**Pull request by alessiofumagalli**
All the tests work correctly and the results are collected. It's mainly the creation of the folder benchmark_2. The only important thing to discuss is related to the file src/porepy/params/data.py.

### CODE REVIEW

**Comment by keileg** [comment]
I agree with Ivar wrt the arxiv. Besides, feel free to merge when you have sorted out the conflicts.

**Comment by alessiofumagalli** [comment]
@keileg, there are no conflicts with the develop branch. Also, we should git tag after the merging, right? If so, I suggest to change the folder name once we know the arXiv number.

**Comment by keileg** [comment]
ok.

**Comment by keileg** [comment]
@alessiofumagalli BTW, also review the comments from Codacy.

**Comment by keileg** [comment]
The codacy errors are stuff that I do not worry to much about.

GitHub still complains about merge conflicts - any ideas on why?

Apart from this, let me know when you're done, then I will bump version number and merge.

**Comment by alessiofumagalli** [comment]
@keileg , you can proceed.

**Comment by alessiofumagalli** [comment]
conflict is solved, once travis agrees you can proceed

**Pull request merged**
