### PR TITLE
Complete documentation using SPHINX-APIDOC

### PR DESCRIPTION
**Pull request by vlipovac**
## Changes

- The style guide for docstrings has been updated.
- A complete documentation of PorePy (using sphinx-apidoc) has been added. If the PR passes, the hosted webpage will contain respective content.
- A new make-target ``complete`` has been added to re-build the doc structure from scratch using apidoc.
- A new *How-To* has been added explaining how to prepare the environment for working with sphinx and how to build docs.

## Types of changes

- [ ] Minor change (e.g., dependency bumps, broken links, etc).
- [ ] Bugfix (non-breaking change which fixes an issue).
- [X] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).
- [ ] Testing (contribution related to testing of existing or new functionality).
- [X] Documentation (contribution related to adding, improving, or fixing documentation).
- [X] Maintenance (e.g., improve logic and performance, remove obsolete code, etc).
- [ ] Other: 

## Checklist

- [ ] The documentation is up-to-date.	
- [ ] Static typing is included in the update.
- [X] This PR does not duplicated existing functionality.
- [ ] The update is covered by the test suite (including tests added in the PR).

## Remarks

The complete documentation of PorePy is included and we can now inspect the results of our work on the grids and geometry subpackages.
As of now, Sphinx throws numerous warnings when building the complete docs, since the remaining docstrings are not reworked.

This update also synchronizes the contents of ``/src/`` in the docs branch with those in the develop branch (downstreaming does not work yet).

The inclusion of the complete docs is mayor milestone towards *professional* documentation 😄 .

### CODE REVIEW

**Comment by vlipovac** [comment]
The file which needs a review is docs/docsrc/howto/howto-build-docs.rst

It contains the How-To for the build procedure.

The changes to the style guide are as discussed during the user group meetings in the last month.

**Comment by keileg** [comment]
I'll have a look, but probably not before Monday.

PS: This PR has, by far, the highest number of modified files I have ever seen.

**Comment by keileg** [comment]
The modifications look good to me. I have one question, though: in the update of the geometry files, I noticed that you had introduced `:obj:` at some points, and also that the number of blank lines when documenting return statements (possibly also in Parameters) seemed to change with the type of the different returned variables. Assuming you have your reasons, and there is a system, I think this should also be included in the how-to. Does that sound fair?

**Comment by vlipovac** [comment]
> The modifications look good to me. I have one question, though: in the update of the geometry files, I noticed that you had introduced `:obj:` at some points, and also that the number of blank lines when documenting return statements (possibly also in Parameters) seemed to change with the type of the different returned variables. Assuming you have your reasons, and there is a system, I think this should also be included in the how-to. Does that sound fair?

In the definition list structure of the params section and in the returns section in case of multiple objects or tuples, only the blank line above the content of a list entry (and below the header) is required for formatting reasons (especially if specifications like shape and default value are given).
I.e.

``<entry-header> : <specifications>``
``<blank-line>``
`` <tab><content>``
``<blak-line-optional>``
``<entry-header> : <specifications>``
``...``

A blank line after the content is optional, might only contribute to readability in the py-file itself (thats an opinion!).
Depending on the theme, it might introduce some vertical whitespace in the HTML.

The usage of ``:obj:`` in the entry-header of return statements with multiple objects supports the quick navigation of the reader.
As of now, the Sphinx settings will include a field ``Return Type:`` which provides the Python return type annotations fully linked.
So one could view the ``:obj:`` as redundant. If the return type annotation is long, say a 4-tuple with individual objects in it, readability in the Return Type field might become an issue.

**Review by keileg — APPROVED** [review]

**Comment by keileg** [comment]
Makes sense, thanks for the clarification.

**Pull request merged**
