### PR TITLE
consider subprocess python package in calling gmsh instead of os, it …

### PR DESCRIPTION
**Pull request by alessiofumagalli**
…should handle also path with spaces

### CODE REVIEW

**Comment by haakon-e** [comment]
If I may suggest using gmsh's own python wrapper for this.
This is what I did to mesh (and refine mesh) in my other PR:
https://github.com/pmgbergen/porepy/blob/437db014d542f45d0a24214a434024c60a72e75c/src/porepy/utils/grid_refinement.py#L63-L71
This is quite clean and easy to understand, in my opinion.

Note that for this, we need the SDK version of gmsh instead of the current PorePy-gmsh requirements. Either way, it will be relevant for my PR for us to decide which way to go on this.
https://github.com/pmgbergen/porepy/blob/437db014d542f45d0a24214a434024c60a72e75c/src/porepy/utils/grid_refinement.py#L47-L55

**Comment by keileg** [comment]
I agree with @haakon-e

**Comment by keileg** [comment]
Btw, that will require modifications to the install instructions, correct?

**Comment by keileg** [comment]
We will most likely go with #367 instead of this one. Let's put it on hold for a little while.

**Comment by keileg** [comment]
Closed, but the same effect should be achieved by #367

**Pull request closed without merging**
