### PR TITLE
Add infinite colors to fracture viz

### PR DESCRIPTION
**Pull request by rbe051**
Just rotate on 20 colors if more than twelve fractures are given

### CODE REVIEW

**Comment by rbe051** [comment]
Pytest in 3.7 breaks because cython is not installed. Why mypy breaks in 3.7 and 3.8 I don't know. But it can not be because of the 1 line I changed?
I suggest merging this PR and figure out why 3.7 and 3.8 breaks in an other PR

**Comment by keileg** [comment]
It likely breaks because the tests are run with numpy 1.20. I will see if I can make this work in a separate branch. Until then, we either enforce np < 1.20, or put this on hold; we will not merge before the tests are running.

**Comment by keileg** [comment]
Support for 3.6 will also be dropped, since np no longer supports it. just as well.

**Review by keileg — APPROVED** [review]
I will take care of the merging once  I have dealt with numpy 1.20 et al

**Pull request merged**
