### PR TITLE
Dbaroli/docker integration

### PR DESCRIPTION
**Pull request by DavideBaroliUniLu**
I add dockerfile to make the image and reproduce the code according to with 
[https://arxiv.org/pdf/1608.07573](url)
Actually the compilation is in progress on [https://hub.docker.com/r/dbaroliyunk/porepy/builds/].

### CODE REVIEW

**Comment by keileg** [comment]
Thanks! Could you add a readme or example so that users will know how to use this?

**Comment by DavideBaroliUniLu** [comment]
Of course, I will modify the Readme adding a small description on how to use it on the different system (wins/mac/linux with and without X11 forward).  However, I need to finish the deploy on DockerHub.

**Comment by alessiofumagalli** [comment]
Hey Davide, can you please give us more details about this branch? And add some documentation how to use these new features? We appreciate it

**Comment by DavideBaroliUniLu** [comment]
Dear both, i modify the readme with full documentation https://github.com/DavideBaroliUniLu/porepy/blob/dbaroli/dockerIntegration/Readme.md.
Please could you wait to accept the request I got some trouble on compiling on cloud VTK 7.0. I am remaking the container and deploying again. I apology for the slow time it takes.

**Comment by keileg** [comment]
Did you close on purpose?

You may want to try vtk install from clinical graphics,

conda install -c clinicalgraphics vtk

For some reason, standard vtk is not our friend.

**Pull request closed without merging**
