### PR TITLE
BUG: Fix uncovered case in division with Ad operators.

### PR DESCRIPTION
**Pull request by keileg**
## Proposed changes

Fix an issue in evaluation of Ad Operator trees, when the parsing ends up with dividing a numpy array by an Ad_array (this is not possible, but the fix introduces workarounds for what seemed the most relevant cases).

## Types of changes

What types of changes does your code introduce to PorePy?
_Put an `x` in the boxes that apply_

- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Testing (contribution related mainly to testing of existing functionality)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR._
- [] I have added tests that prove my fix is effective or that my feature works
- [X] I have added necessary documentation 
- [X] I have checked that I have not duplicated existing functionality

## Further comments
There may be other closely related cases not covered by the current fix. These are not included in the current PR, but are indicated in the comments of the new implementation. Moreover, the new implementation should raise error messages if such uncovered cases are encountered (previously, such cases were silently ignored).

### CODE REVIEW

**Comment by IvarStefansson** [comment]
I cannot see that there are any new tests. This might be fine, but I would prefer for the box in the PR description to be unchecked

**Comment by keileg** [comment]
Fair point, unticked. 

This part of the code is not explicitly tested. That's a big fixme, what we will need is a systematic check of all combinations of different operators, operations (+,-,etc.), and combinations with numpy arrays, scalars (floats, ints, etc.). This should make the code more robust, and also put us in a position to remove the spurious errors that we sometimes get in evaluation of Ad operators (the current PR is an example). However, this will be a major undertaking that I have never had the time and energy to start working on, and I'm afraid it will take some more time, but we need to get there.

**Comment by IvarStefansson** [comment]
I think setting up the tests might not be too much work if done cleverly. But fixing the bugs we might identify could require substantial work, yes. Should we make this an issue?

**Review by IvarStefansson — APPROVED** [review]

**Comment by keileg** [comment]
Created #645. Let's add to the list if we see more needs.

**Pull request merged**
