### PR TITLE
Added functionality for extracting parameter arrays from edges dictionaries

### PR DESCRIPTION
**Pull request by jhabriel**
This new functionality is meant to work as `pp.ad.ParameterArray`, but instead of picking up values from subdomain dictionaries, now it is also possible to extract parameter arrays from edge dictionaries. The inputs are the parameter keyword, the array keyword, and then the edge list or the grid bucket.

### CODE REVIEW

**Comment by IvarStefansson** [comment]
The `edges` parameter of `ParameterArray` was just added in #551. Does it cover this functionality?

**Comment by jhabriel** [comment]
It certainly does.  I did not realize that the functionality was extended. And indeed, it makes much more sense to have only one class taking care of extracting the parameters of both nodes and edges. From what I noticed, there is a tendency to avoid passing the `GridBucket` and stick to passing the `grids_list`and `edges_list` instead. Is there any particular reason for this? Also, is there a way to catching an error if both `grids_list` and `edges_list` are passed at the same time?

**Comment by IvarStefansson** [comment]
No, I don't think so. One could reasonably wish to use some parameter for both grids and edges.

**Comment by jhabriel** [comment]
I agree. I did not contemplate that possibility. Very well then, I will close this PR. Thanks, Ivar.

**Pull request closed without merging**
