### PR TITLE
Names

### PR DESCRIPTION
**Pull request by IvarStefansson**
New naming conventions:
f -> source
k -> perm
beta_n -> discharge
c -> stiffness
a -> aperture
Simplification of tensors.

I think I have changed (almost) all occurrences in the code, there are definitely some left in the documentation. I have not moved the couplings, did we agree on how to do this?

### CODE REVIEW

**Comment by rbe051** [comment]
Why discharge and not flux?

**Comment by keileg** [comment]
This should be seen in connection with #24 - we don't want to rewrite all data structures twice in a week. Runar and I have some ideas on how to approach #24, so let's discuss tomorrow.

**Comment by IvarStefansson** [comment]
"Discharges" because "flux" is taken in the FV discretizations

**Comment by keileg** [comment]
This is superseded by #28 The branch will be kept and extended.

**Pull request closed without merging**
