### PR TITLE
DofManager-bugfix

### PR DESCRIPTION
**Pull request by pschultzendorff**
## Proposed changes

This PR fixes a bug in the ``DofManager.get_variable_values`` method. A for-loop, which was incorrectly looping over the key, value pairs of a dict, now only loops over the keys.

Also, a basic test is added to check that the method works.

## Types of changes

What types of changes does this PR introduce to PorePy?

- [ ] Minor change (e.g., dependency bumps, broken links, etc).
- [x] Bugfix (non-breaking change which fixes an issue).
- [ ] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).
- [x] Testing (contribution related to testing of existing or new functionality).
- [ ] Documentation (contribution related to adding, improving, or fixing documentation).
- [ ] Maintenance (e.g., improve logic and performance, remove obsolete code, etc).
- [ ] Other: 

## Checklist

_Put an `x` in the boxes that apply or explain briefly why the box is not relevant._

- [x] The documentation is up-to-date.	
- [x] Static typing is included in the update.
- [x] This PR does not duplicated existing functionality.
- [x] The update is covered by the test suite (including tests added in the PR).

### CODE REVIEW

**Review by IvarStefansson — COMMENTED** [review]
Nice! Any particular reason for placing the test in the ad folder?

**Comment by pschultzendorff** [comment]
> Nice! Any particular reason for placing the test in the ad folder?

I somehow thought that the DofManager was also in the ad submodule when creating the test. Will move it to the general test folder. Unless there are some other tests for the DofManager that I could add it to. I didn't find any before, but I also didn't look exhaustively.

**Comment by IvarStefansson** [comment]
> > Nice! Any particular reason for placing the test in the ad folder?
> 
> I somehow thought that the DofManager was also in the ad submodule when creating the test. Will move it to the general test folder. Unless there are some other tests for the DofManager that I could add it to. I didn't find any before, but I also didn't look exhaustively.

I didn't find any either. I suppose you'll just have to make a new one, probably in unit.

**Comment by pschultzendorff** [comment]
I moved the test to the main unit test directory and fixed the typing error.

**Review by IvarStefansson — APPROVED** [review]

**Pull request merged**
