### PR TITLE
Codacy fix

### PR DESCRIPTION
**Pull request by rbe051**
Fixed all assertions for Unittests so codacy do not complain

### CODE REVIEW

**Comment by keileg** [comment]
Great! Although Codacy is ungrateful.

**Comment by keileg** [comment]
Any idea why coverage declined?

**Comment by rbe051** [comment]
Good question.. I will invesstigate

**Comment by rbe051** [comment]
It is the test that I removed that did no testing. I removed it because it had no asserts

**Comment by keileg** [comment]
How can that decrease effective coverage with 0.5%?

**Comment by rbe051** [comment]
I don't know how coveralls calculate this percentage. But if you look at the previous commit ffc2bfc it passed the coveralls.

It is strange that it drops this much, since the removed test does the same as the one I kept. 
However, I can't figure out in coveralls where the percentage drops. Should it not say so somewhere?

**Comment by rbe051** [comment]
I think there must have been a bug in Codacy. Now everything is fine. Closing pull-request

**Pull request merged**
