### PR TITLE
Version bump

### PR DESCRIPTION
**Pull request by alessiofumagalli**
We forgot to change the name of the folder and to update the readme with the arxiv paper. I amend the last commit (version bump) and add these two small changes. Since we use the commit as reference, maybe this will solve the merging by avoiding a commit. Not sure.

git merge branch-name --no-commit --no-ff

### CODE REVIEW

**Comment by alessiofumagalli** [comment]
@keileg , what about this pull request?

**Comment by keileg** [comment]
I have completely forgotten this one. @alessiofumagalli Can you remind me of the status?

**Comment by alessiofumagalli** [comment]
@keileg , it should be something small.. We forgot to rename the folder after the mortar paper was on arxiv. I check it, one sec

**Comment by keileg** [comment]
So it is not referred to by its arXiv ID? Sounds like a trivial fix, except that there seems to be some conflicts.

**Comment by alessiofumagalli** [comment]
now I fixed them, if you want I can merge after all the checks are finished

**Pull request merged**
