### PR TITLE
BLD: GH action runs on Python 3.10,*, not fixed to 3.10.6

### LINKED ISSUE #733: Change python version from 3.10.6 to 3.10 when mypy allows it

### PR DESCRIPTION
**Pull request by keileg**
This fixes a temporary requirement that actions were run on Python > 3.10.7, relating to an issue in mypy.

Resolves #733. 

## Proposed changes

Contributions to PorePy are highly appreciated. Clearly explain to the maintainers why this pull request (PR) is needed and why it should be accepted. If this PR solves an issue, explain how it is done. Please, also summarise the changes to the code. 

## Types of changes

What types of changes does this PR introduce to PorePy?
_Put an `x` in the boxes that apply_

- [ ] Minor change (e.g., dependency bumps, broken links, etc).
- [ ] Bugfix (non-breaking change which fixes an issue).
- [ ] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).
- [ ] Testing (contribution related to testing of existing or new functionality).
- [ ] Documentation (contribution related to adding, improving, or fixing documentation).
- [ ] Maintenance (e.g., improve logic and performance, remove obsolete code, etc).
- [x] Other: Github actions.

## Checklist

_Put an `x` in the boxes that apply or explain briefly why the box is not relevant._

- [ ] The documentation is up-to-date: Not relevarnt, only GH actions are updated.
- [ ] Static typing is included in the update: Not relevarnt, only GH actions are updated.
- [ ] This PR does not duplicated existing functionality: Not relevarnt, only GH actions are updated.
- [ ] The update is covered by the test suite (including tests added in the PR): Not relevarnt, only GH actions are updated.

### CODE REVIEW

**Comment by keileg** [comment]
@IvarStefansson: I have to check if this works by triggering a GH action. If it works, it should be uncontroversial, if not, I suggest we stall the PR until mypy is sufficiently updated.

I think you can unsubscribe from this PR, then I will let you know when it is ready.

**Comment by keileg** [comment]
@IvarStefansson: The PR should be working and ready for (a trivial) review

**Comment by jhabriel** [comment]
@keileg: Do we want to update the mypy version in the requirements? 

Most likely, old versions of mypy will break with 3.10.7.

**Comment by keileg** [comment]
Fair point, I have updated.

**Review by IvarStefansson — APPROVED** [review]

**Pull request merged**
